/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef } from "react";
import { useGLTF } from "@react-three/drei";

export const Rocketship = forwardRef((props, ref) => {
    const { nodes, materials } = useGLTF("/Rocketship.glb");

    return (
        <group ref={ref} {...props} position={[0, 0, -150]}>
            <group position={[0, -10, 0]} dispose={null}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.RocketShip_mesh.geometry}
                    material={materials.RocketShip_mat}
                />
            </group>
        </group>
    );
});

useGLTF.preload("/Rocketship.glb");
